server:
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
    servicePortHttp: 80
    servicePortHttps: 443

configs:
  params:
    server.insecure: true

  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true
