clusterName: elasticsearch-cluster
nodeGroup: master

service:
  type: ClusterIP
  ports:
    http: 9200
    transport: 9300

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

replicas: 1

persistence:
  enabled: false