apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KCSJhdXRocyI6IHsNCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHt9DQoJfSwNCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwNCgkiY3VycmVudENvbnRleHQiOiAiZGVmYXVsdCIsDQoJInBsdWdpbnMiOiB7DQoJCSIteC1jbGktaGludHMiOiB7DQoJCQkiZW5hYmxlZCI6ICJ0cnVlIg0KCQl9DQoJfQ0KfQ0K