apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  labels:
    app: jenkins-agent
  namespace: jenkins
spec:
  securityContext:    
    fsGroup: 1000 
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["sleep"]
    args: ["999999"]
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    - name: workspace-volume
      mountPath: /workspace

  - name: git
    image: alpine/git:latest
    command: ["sleep"]
    args: ["999999"]
    tty: true
    env:
    - name: "HOME"
      value: "/workspace"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    volumeMounts:
    - name: workspace-volume
      mountPath: /workspace

  - name: "jnlp"
    image: "jenkins/inbound-agent:latest-jdk17"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    env:
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/workspace"
    volumeMounts:
    - name: "workspace-volume"
      mountPath: "/workspace" 

  - name: yq
    image: mikefarah/yq:4.43.1
    command: ["sleep"]
    args: ["999999"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    volumeMounts:
    - name: workspace-volume
      mountPath: /workspace 

  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockerhub-secret
      items:
        - key: .dockerconfigjson
          path: config.json
  - name: workspace-volume
    emptyDir: {}
