vote:
  image: quang47/voting-app_vote
  tag: 313f4e5c
  replicaCount: 1
result:
  image: quang47/voting-app_result
  tag: 313f4e5c
  replicaCount: 1
worker:
  image: dockersamples/examplevotingapp_worker
  tag: latest
  replicaCount: 1
redis:
  image: redis
  tag: alpine
db:
  image: postgres
  tag: 15-alpine
  postgresUser: postgres
  postgresPassword: postgres
  persistence:
    enabled: true
    size: 1Gi
