vote:
  image: dockersamples/examplevotingapp_vote
  tag: latest
  replicaCount: 1
result:
  image: dockersamples/examplevotingapp_result
  tag: latest
  replicaCount: 1
worker:
  image: dockersamples/examplevotingapp_worker
  tag: latest
  replicaCount: 1
redis:
  image: redis
  tag: alpine
db:
  image: postgres
  tag: 15-alpine
  postgresUser: postgres
  postgresPassword: postgres
  persistence:
    enabled: true
    size: 1Gi
