apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
        fluentd.io/parser: "json"
        fluentd.io/tag: "result-app"    
    spec:
      containers:
        - name: result
          image: "{{ .Values.result.image }}:{{ .Values.result.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 8081
    targetPort: 80
    nodePort: 31001
  selector:
    app: result