apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec: 
  revisionHistoryLimit: 2
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image }}:{{ .Values.worker.tag }}"
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_HOST
              value: db